FROM ekidd/rust-musl-builder:nightly-2021-01-01 as builder

ADD --chown=rust:rust . /didkit
ADD --chown=rust:rust ./ssi /ssi
WORKDIR /didkit/http

ENV CARGO_NET_GIT_FETCH_WITH_CLI=true
RUN cargo build --release

FROM alpine
COPY --from=builder /didkit/target/x86_64-unknown-linux-musl/release/didkit-http /usr/local/bin/

ENTRYPOINT ["didkit-http"]
