FROM ekidd/rust-musl-builder as builder

ADD --chown=rust:rust . /didkit
ADD --chown=rust:rust ./ssi /ssi
WORKDIR /didkit/cli

ENV CARGO_NET_GIT_FETCH_WITH_CLI=true
RUN cargo build --release

FROM alpine
COPY --from=builder /didkit/target/x86_64-unknown-linux-musl/release/didkit didkit
ENTRYPOINT ["./didkit"]


